manager/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

manager/manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
    path('', include('account.urls')),
]

manager/project/urls.py
from django.urls import path

from . import views

app_name = 'project'

urlpatterns = [
    # main page
    path('', views.index, name='index'),
    # page where all projects are listed
    path('projects/', views.projects, name='projects'),
    # page to add a new project
    path('add_project/', views.add_project, name='add_project'),
    # detail page for a specific   project
    path('projects/<int:pk>/', views.project, name='project'),
    # page to edit an existing project
    path('projects/<int:pk>/edit/', views.edit_project, name='edit_project'),
    # page to delete a  project
    path('projects/<int:pk>/delete/', views.delete_project, name='delete_project'),
    # search project
    path('search_project/', views.search_projects, name='search_projects'),
    # add a todolist in a project
    path('projects/<int:project_id>/add_todolist/', views.add_todolist, name='add_todolist'),
    # see a detail for a specific todolist
    path('projects/<int:project_id>/todolist/<int:pk>/', views.todolist, name='todolist'),
    # edit a todolist
    path('projects/<int:project_id>/todolist/<int:pk>/edit_todolist/', views.edit_todolist, name='edit_todolist'),
    # delete a project
    path('projects/<int:project_id>/todolist/<int:pk>/delete_todolist/', views.delete_todolist, name='delete_todolist'),
    # add a task
    path('projects/<int:project_id>/todolist/<int:todolist_id>/add_task/', views.add_task, name='add_task'),
    # detail for  task
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/', views.task_detail,
         name='task_detail'),
    # edit a task
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/edit_task/', views.edit_task,
         name='edit_task'),
    # delete a task
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/delete_task/', views.delete_task,
         name='delete_task'),
    # remove a task material resource
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/<int:material_id>/delete/',
         views.delete_task_material, name='delete_task_material'),
    # remove a task team
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/<int:team_id>/delete_team/',
         views.delete_task_team, name='delete_task_team'),

    # url to see  agents
    path('agents/', views.agents, name='agents'),
    # add agent
    path('add_agent/', views.add_agent, name='add_agent'),
    # edit agent
    path('agents/<int:pk>/edit/', views.edit_agent, name='edit_agent'),
    # delete agent
    path('agents/<int:pk>/delete/', views.delete_agent, name='delete_agent'),
    # search an agent
    path('search/', views.search_agents, name='search_agents'),
    # url to see  teams
    path('teams/', views.teams, name='teams'),
    path('search/', views.search_teams, name='search_teams'),
    # add a team
    path('add_team/', views.add_team, name='add_team'),
    # team details
    path('teams/<int:team_id>/', views.team_details, name='team_details'),
    # edit team
    path('teams/<int:team_id>/edit/', views.edit_team, name='edit_team'),
    # delete team
    path('teams/<int:team_id>/delete/', views.delete_team, name='delete_team'),
    # delete a team member
    path('teams/<int:team_id>/<int:member_id>/delete', views.delete_team_member, name='delete_team_member'),
    # list materials resources
    path('materials/', views.materials, name='materials'),
    # add material
    path('add_material/', views.add_material, name='add_material'),
    # edit material
    path('materials/<int:material_id>/edit', views.edit_material, name='edit_material'),
    # delete material
    path('materials/<int:material_id>/delete', views.delete_material, name='delete_material'),
    # list softwares
    path('softwares/', views.softwares, name='softwares'),
    # add a software
    path('add_software/', views.add_software, name='add_software'),
    # edit a specific software
    path('softwares/<int:software_id>/edit', views.edit_software, name='edit_software'),
    # delete a software
    path('softwares/<int:software_id>/delete', views.delete_software, name='delete_software'),
    # search software
    path('search_software/', views.search_software, name='search_software'),
    # list reunions
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions', views.reunions,
         name='reunions'),
    # add reunion
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/add_reunion',
         views.add_reunion, name='add_reunion'),
    # reunion detail
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/<int:reunion_id>/',
         views.reunion_detail, name='reunion_detail'),
    # edit a reunion
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/<int:reunion_id>/edit/',
         views.edit_reunion, name='edit_reunion'),
    # delete reunion
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/<int:reunion_id>/delete',
         views.delete_reunion, name='delete_reunion'),

    # create a repport for reunion
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/<int:reunion_id>/create_report/',
        views.create_report, name='create_report'),
    # report detail
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/<int:reunion_id>/<int:report_id>/',
         views.report_detail, name='report_detail'),
    # delete report
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/<int:reunion_id>/<int:report_id>/delete/',
         views.delete_report, name='delete_report'),
    # edit a report
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/<int:reunion_id>/<int:report_id>/edit/',
         views.edit_report, name='edit_report'),
    # add a product to task
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/', views.add_product,
         name='add_product'),
]

manager/project/views.py
from datetime import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.urls import reverse

from .models import Project, Todolist, Task, Agent, Team, MaterialResource, Software, Reunion, MeetingReport, Product
from django.contrib.auth.decorators import login_required


# la vue de la page d'acceuil
def index(request):
    return render(request, 'project/index.html')


# la vue pour voir la liste des projets disponibles
@login_required
def projects(request):
    projects_list = Project.objects.filter(created_by=request.user)

    return render(request, 'project/projects_list.html', {
        'projects_list': projects_list
    })


# the view to see a detail for a specific project
@login_required
def project(request, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=pk)

    return render(request, 'project/project_detail.html', {
        'project': project
    })


# la vue por ajouter un projet
@login_required
def add_project(request):
    if request.method == 'POST':
        project = Project(name=request.POST['name'],
                          description=request.POST['description'],
                          start_date=request.POST['startdate'],
                          deadline=request.POST['deadline'],
                          created_by=request.user)  # Fournir l'utilisateur actuellement connecté
        project.save()
        return redirect('/projects/')

    return render(request, 'project/add_project.html')


@login_required
def edit_project(request, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')
        startdate_str = request.POST.get('startdate', '')
        deadline_str = request.POST.get('deadline', '')

        if name:
            project.name = name
            project.description = description
            project.start_date = datetime.strptime(startdate_str, '%Y-%m-%d').date()
            project.deadline = datetime.strptime(deadline_str, '%Y-%m-%d').date()

            project.save()

            return redirect('/projects/')

    return render(request, 'project/edit_project.html', {
        'project': project
    })


@login_required
def delete_project(request, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=pk)
    project.delete()

    return redirect('/projects/')


@login_required
def search_projects(request):
    query = request.GET.get('quest')
    projects = Project.objects.filter(created_by=request.user)

    if query:
        projects = projects.filter(created_by=request.user).filter(name__icontains=query)

    return render(request, 'project/search_results.html', {'projects': projects})


@login_required
def todolist(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)

    return render(request, 'project/todolist/todolist.html', {
        'project': project,
        'todolist': todolist
    })


# the view for adding a todolist
@login_required
def add_todolist(request, project_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)

    if request.method == 'POST':
        name = request.POST.get('name', '').strip()  # Utilisez strip() pour supprimer les espaces blancs
        description = request.POST.get('description', '')

        if name:  # Vérifiez si le nom n'est pas une chaîne vide
            todolist = Todolist(project=project, name=name, description=description, created_by=request.user)
            todolist.save()
            return redirect(f'/projects/{project_id}/')

    return render(request, 'project/todolist/add_todolist.html', {'project': project})


# view to edit a todolist
@login_required
def edit_todolist(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')
        if name:
            todolist.name = name
            todolist.description = description

            todolist.save()
            return redirect(f'/projects/{project_id}/todolist/{pk}')
    return render(request, 'project/todolist/edit_todolist.html', {
        'project': project,
        'todolist': todolist
    })


# the view to delete a todolist
@login_required
def delete_todolist(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)

    todolist.delete()

    return redirect(f'/projects/{project_id}/')


@login_required
def add_task(request, project_id, todolist_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)

    if request.method == 'POST':
        task = Task(name=request.POST['name'],
                    description=request.POST['description'],
                    start_date=request.POST['startdate'],
                    deadline=request.POST['deadline'],
                    created_by=request.user,
                    project=project,
                    todolist=todolist,

                    )  # Fournir l'utilisateur actuellement connecté
        task.save()

        return redirect(f'/projects/{project_id}/todolist/{todolist_id}')

    return render(request, 'project/task/add_task.html', {
        'project': project,
        'todolist': todolist
    })


@login_required
def task_detail(request, project_id, todolist_id, task_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)

    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=task_id)

    if request.GET.get('is_done', ''):
        task.is_done = True
        task.save()

    if request.method == 'POST':
        materials_ids = request.POST.getlist('material_resources')
        task.material_resources.add(*materials_ids)
        teams_ids = request.POST.getlist('teams')
        task.teams.add(*teams_ids)

    available_materials = MaterialResource.objects.exclude(id__in=task.material_resources.all())
    available_teams = Team.objects.exclude(id__in=task.teams.all())

    softwares = task.softwares.all()
    teams = task.teams.all()


    return render(request, 'project/task/task_detail.html', {
        'project': project,
        'todolist': todolist,
        'task': task,
        'available_materials': available_materials,
        'softwares': softwares,
        'teams': teams,
        'available_teams': available_teams,

    })


@login_required
def edit_task(request, project_id, todolist_id, task_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=task_id)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')
        startdate_str = request.POST.get('startdate', '')
        deadline_str = request.POST.get('deadline', '')

        if name:
            task.name = name
            task.description = description
            task.start_date = datetime.strptime(startdate_str, '%Y-%m-%d').date()
            task.deadline = datetime.strptime(deadline_str, '%Y-%m-%d').date()
            task.save()

            return redirect(f'/projects/{project_id}/todolist/{todolist_id}/{task_id}/detail/')

    return render(request, 'project/task/edit_task.html', {
        'task': task
    })


@login_required
def delete_task(request, project_id, todolist_id, task_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=task_id)
    task.delete()

    return redirect(f'/projects/{project_id}/todolist/{todolist_id}/')


@login_required
def delete_task_material(request, project_id, todolist_id, task_id, material_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=task_id)

    material = get_object_or_404(MaterialResource, pk=material_id)

    if material in task.material_resources.all():
        task.material_resources.remove(material)

    return redirect(f'/projects/{project_id}/todolist/{todolist_id}/{task_id}/detail/')


@login_required
def delete_task_team(request, project_id, todolist_id, task_id, team_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=task_id)

    team = get_object_or_404(Team, pk=team_id)

    if team in task.teams.all():
        task.teams.remove(team)

    return redirect(f'/projects/{project_id}/todolist/{todolist_id}/{task_id}/detail/')


#  view for agents
@login_required
def agents(request):
    agents = Agent.objects.all

    return render(request, 'project/agent/agents.html', {
        'agents': agents
    })


@login_required
def add_agent(request):
    error_message = None

    if request.method == 'POST':
        matricule = request.POST.get('matr')

        # Vérifie si un agent avec le même matricule existe déjà

manager/project/templates/project/team/add_team.html
{% extends 'project/base.html' %}

{% block content %}
    <h1 class="mb-6 px-8 text-3xl">Add team</h1>
     <form class="mt-6 px-8 space-y-4 text-start" method="post" action=".">
        {% csrf_token %}
        <div>
            <label for="name">Nom</label><br>
            <input id="name" name="name" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label for="leader">Leader</label><br>
            <select id="leader" name="leader" class="w-full py-4 px-6 bg-slate-500 text-white">
                <option value="">Select a leader</option>
                {% for agent in agents %}
                    <option value="{{ agent.id }}">{{ agent.first_name }} {{ agent.last_name }}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <button class="py-4 px-8 bg-green-600 hover:bg-green-400 text-white hover:text-gray-800">Create</button>
        </div>
    </form>
{% endblock %}

manager/project/templates/project/team/edit_team.html
{% extends 'project/base.html' %}

{% block content %}
    <h1 class="mb-6 px-8 text-3xl">Edit team</h1>
    <form class="mt-6 px-8 space-y-4 text-start" method="post" action="">
        {% csrf_token %}
        <div>
            <label for="name">Nom</label><br>
            <input id="name" name="name" value="{{ team.name }}" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label for="leader">Leader</label><br>
            <select id="leader" name="leader" class="w-full py-4 px-6 bg-slate-500 text-white">
                <option value="">{{ team.leader }}</option>
                {% for agent in agents %}
                    <option value="{{ agent.id }}">{{ agent.first_name }} {{ agent.last_name }}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <button class="py-4 px-8 bg-green-600 hover:bg-green-400 text-white hover:text-gray-800">Enregistrer</button>
        </div>
    </form>
{% endblock %}

manager/project/templates/project/team/search_results.html
{% extends 'project/base.html' %}

{% block content %}

    <div class="w-full flex justify-center p-1 mb-4">
        <div class="relative w-full">
            <form method="GET" action="{% url 'project:search_agents' %}">
                <input type="text" name="q" class="w-full backdrop-blur-sm bg-white/20 py-2 pl-10 pr-4 rounded-lg focus:outline-none border-2 border-gray-100 focus:border-green-600 transition-colors duration-300" placeholder="Search...">
                <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                    <button type="submit">
                        <svg class="w-4 h-4 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="mt-6 w-full grid grid-cols-4 gap-4">
       {% for team in teams %}
            <div class="py-6 px-6 bg-slate-200  rounded-lg">
                <a href="#">
                    <h2 class="mb-4 text-xl">{{ team.name }}</h2>

                    <p class="text-sm text-slate-600">
                        {{ team.leader }}
                    </p>
                </a>
            </div>
       {% empty %}
             <div>Aucune équipe trouvée.</div>-->
       {% endfor %}
    </div>




{% endblock %}

manager/project/templates/project/team/team_details.html
{% extends 'project/base.html' %}


{% block content %}
    <h1 class=" text-start mb-6 text-3xl bd-1">Team : {{ team.name }}</h1>
     <div class="flex items-start mb-6 px-4">
        <a href="{% url 'project:edit_team' team.id %}" class="py-4  px-8 rounded bg-sky-600 hover:bg-sky-400 text-white hover:text-gray-800 inline-block">Editer</a>
        <a href="{% url 'project:delete_team' team.id %}" class="py-4  px-8 rounded bg-amber-600 hover:bg-amber-400 ml-6 text-white hover:text-gray-800 inline-block">Supprimer</a>
    </div>

    <p class="border text-start  mb-4 text-xl border-gray-500 border-1 p-4 ">Leader : {{ team.leader }}</p>



    <div class="-mx-3 flex mt-6 mb-20 flex-wrap">
        <div class="w-full px-3 sm:w-1/2">
            <h1 class="mb-4 text-start bd-1 text-3xl">Team members</h1>
            <table class="min-w-full border-collapse block md:table">
                <thead class="block md:table-header-group">
                    <tr class="border border-grey-500 md:border-none block md:table-row absolute -top-full md:top-auto -left-full md:left-auto  md:relative ">
                        <th class="bg-slate-800 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">FirstName</th>
                        <th class="bg-slate-800 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">LastName</th>
                        <th class="bg-slate-800 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">Qualification</th>
                        <th class="bg-slate-800 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">Actions </th>
                    </tr>
                </thead>
                <!--  ===========      -->
                 <tbody class="  block md:table-row-group">
                    {% for member in team.members.all %}
                         <tr class="bg-slate-600 text-white border border-grey-500 md:border-none block md:table-row">
                            <td class="p-2 md:border md:border-grey-500 text-left block md:table-cell"><span class="inline-block w-1/3 md:hidden font-bold">FirstName</span> {{  member.first_name }}</td>
                            <td class="p-2 md:border md:border-grey-500 text-left block md:table-cell"><span class="inline-block w-1/3 md:hidden font-bold">LastName</span> {{  member.last_name }} </td>
                            <td class="p-2 md:border md:border-grey-500 text-left block md:table-cell"><span class="inline-block w-1/3 md:hidden font-bold">Qualification</span> {{  member.qualification }} </td>
                            <td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
                                <span class="inline-block w-1/3 md:hidden font-bold">Actions</span>
                                <a href="{% url 'project:delete_team_member' team.id member.id %}"><button class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 border border-red-500 rounded">Remove</button></a>
                            </td>
                         </tr>
                    {% empty %}
                        <tr class="bg-slate-300 ">
                          <td class="p-2 md:border md:border-grey-500 text-center block md:table-cell"colspan="7">Aucun membre trouvé.</td>
                        </tr>
                    {% endfor %}
                 </tbody>

            </table>
        </div>

        <div class="w-full px-3 sm:w-1/2">
            <h1 class="mb-4 text-start ml-8 bd-1 text-2xl">Select and submit to add members</h1>
             <form class="mt-4 px-8 space-y-4 text-start" method="post" >
                {% csrf_token %}
                <div>
                    <select  multiple name="members" class="w-full rounded-md py-2 px-4 bg-slate-500 text-white">
                         {% for member in available_members %}
                               <option value="{{ member.id }}">{{ member }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div>
                    <button class="py-4 px-8 w-full rounded-lg  bg-green-600 hover:bg-green-400 text-white hover:text-gray-800">Ajouter</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

manager/project/templates/project/team/teams.html
{% extends 'project/base.html' %}

{% block content %}
     <div class="w-full flex justify-between items-center p-3">
      <h2 class="text-xl font-semibold">Teams</h2>
        <a href="{% url 'project:add_team' %}" >
            <button id="openModalBtn" class="flex items-center bg-green-600  hover:bg-green-400  text-white hover:text-gray-800   border border-fuchsia-00 hover:border-green-100  font-semibold py-2 px-4 rounded-md transition-colors duration-300">
                <svg class="w-4 h-4 mr-2 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
                </svg>
                <p class="text-white">New Team</p>
            </button>
        </a>
    </div>


    <div class="w-full flex justify-center p-1 mb-4">
        <div class="relative w-full">
            <form method="GET" action="{% url 'project:search_teams' %}">
                <input type="text" name="q" class="w-full backdrop-blur-sm bg-white/20 py-2 pl-10 pr-4 rounded-lg focus:outline-none border-2 border-gray-100 focus:border-green-600 transition-colors duration-300" placeholder="Search...">
                <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                    <button type="submit">
                        <svg class="w-4 h-4 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
    </div>

     <div class="mt-6 w-full text-white grid grid-cols-4 gap-4">
       {% for team in teams %}
            <div class="py-6 px-6 bg-slate-500  rounded-lg">
                <a href="{% url 'project:team_details' team.id %}">
                    <h2 class="mb-4 text-xl">{{ team.name }}</h2>

                    <p class="text-sm text-slate-200">
                        Led by {{ team.leader }}
                    </p>
                </a>
            </div>
       {% endfor %}
    </div>

{% endblock %}