manager/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

manager/manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
    path('', include('account.urls')),
]

manager/project/urls.py
from django.urls import path

from . import views

app_name = 'project'

urlpatterns = [
    # main page
    path('', views.index, name='index'),
    # page where all projects are listed
    path('projects/', views.projects, name='projects'),
    # page to add a new project
    path('add_project/', views.add_project, name='add_project'),
    # detail page for a specific   project
    path('projects/<int:pk>/', views.project, name='project'),
    # page to edit an existing project
    path('projects/<int:pk>/edit/', views.edit_project, name='edit_project'),
    # page to delete a  project
    path('projects/<int:pk>/delete/', views.delete_project, name='delete_project'),
    # search project
    path('search_project/', views.search_projects, name='search_projects'),
    # add a todolist in a project
    path('projects/<int:project_id>/add_todolist/', views.add_todolist, name='add_todolist'),
    # see a detail for a specific todolist
    path('projects/<int:project_id>/todolist/<int:pk>/', views.todolist, name='todolist'),
    # edit a todolist
    path('projects/<int:project_id>/todolist/<int:pk>/edit_todolist/', views.edit_todolist, name='edit_todolist'),
    # delete a project
    path('projects/<int:project_id>/todolist/<int:pk>/delete_todolist/', views.delete_todolist, name='delete_todolist'),
    # add a task
    path('projects/<int:project_id>/todolist/<int:todolist_id>/add_task/', views.add_task, name='add_task'),
    # detail for  task
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/', views.task_detail,
         name='task_detail'),
    # edit a task
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/edit_task/', views.edit_task,
         name='edit_task'),
    # delete a task
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/delete_task/', views.delete_task,
         name='delete_task'),
    # remove a task material resource
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/<int:material_id>/delete/',
         views.delete_task_material, name='delete_task_material'),
    # remove a task team
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/<int:team_id>/delete_team/',
         views.delete_task_team, name='delete_task_team'),

    # url to see  agents
    path('agents/', views.agents, name='agents'),
    # add agent
    path('add_agent/', views.add_agent, name='add_agent'),
    # edit agent
    path('agents/<int:pk>/edit/', views.edit_agent, name='edit_agent'),
    # delete agent
    path('agents/<int:pk>/delete/', views.delete_agent, name='delete_agent'),
    # search an agent
    path('search/', views.search_agents, name='search_agents'),
    # url to see  teams
    path('teams/', views.teams, name='teams'),
    path('search/', views.search_teams, name='search_teams'),
    # add a team
    path('add_team/', views.add_team, name='add_team'),
    # team details
    path('teams/<int:team_id>/', views.team_details, name='team_details'),
    # edit team
    path('teams/<int:team_id>/edit/', views.edit_team, name='edit_team'),
    # delete team
    path('teams/<int:team_id>/delete/', views.delete_team, name='delete_team'),
    # delete a team member
    path('teams/<int:team_id>/<int:member_id>/delete', views.delete_team_member, name='delete_team_member'),
    # list materials resources
    path('materials/', views.materials, name='materials'),
    # add material
    path('add_material/', views.add_material, name='add_material'),
    # edit material
    path('materials/<int:material_id>/edit', views.edit_material, name='edit_material'),
    # delete material
    path('materials/<int:material_id>/delete', views.delete_material, name='delete_material'),
    # list softwares
    path('softwares/', views.softwares, name='softwares'),
    # add a software
    path('add_software/', views.add_software, name='add_software'),
    # edit a specific software
    path('softwares/<int:software_id>/edit', views.edit_software, name='edit_software'),
    # delete a software
    path('softwares/<int:software_id>/delete', views.delete_software, name='delete_software'),
    # search software
    path('search_software/', views.search_software, name='search_software'),
    # list reunions
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions', views.reunions,
         name='reunions'),
    # add reunion
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/add_reunion',
         views.add_reunion, name='add_reunion'),
    # reunion detail
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/<int:reunion_id>/',
         views.reunion_detail, name='reunion_detail'),
    # edit a reunion
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/<int:reunion_id>/edit/',
         views.edit_reunion, name='edit_reunion'),
    # delete reunion
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/<int:reunion_id>/delete',
         views.delete_reunion, name='delete_reunion'),

    # create a repport for reunion
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/<int:reunion_id>/create_report/',
        views.create_report, name='create_report'),
    # report detail
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/<int:reunion_id>/<int:report_id>/',
         views.report_detail, name='report_detail'),
    # delete report
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/<int:reunion_id>/<int:report_id>/delete/',
         views.delete_report, name='delete_report'),
    # edit a report
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/reunions/<int:reunion_id>/<int:report_id>/edit/',
         views.edit_report, name='edit_report'),
    # add a product to task
    path('projects/<int:project_id>/todolist/<int:todolist_id>/<int:task_id>/detail/', views.add_product,
         name='add_product'),
]

manager/project/models.py
import datetime

from django.core.exceptions import ValidationError
from django.db import models

import account.models

from account.models import User


def validate_start_date(value):
    if value < datetime.date.today():
        raise ValidationError("La date de début ne peut pas être dans le passé.")


def validate_deadline_date(value):
    if value < datetime.date.today():
        raise ValidationError("La date de début ne peut pas être dans le passé.")


class Project(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField()
    deadline = models.DateField()
    created_by = models.ForeignKey(account.models.User, related_name='projects', on_delete=models.CASCADE, )

    def __str__(self):
        return self.name

    def clean(self):
        if self.deadline < self.start_date:
            raise ValidationError("La date de fin ne peut pas être inférieure à la date de début.")
        super().clean()


class Todolist(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    description = models.TextField(blank=True, null=True)
    project = models.ForeignKey(Project, related_name='todolist', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='todolist', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField()
    deadline = models.DateField()
    is_done = models.BooleanField(default=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    todolist = models.ForeignKey(Todolist, related_name='tasks', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='tasks', on_delete=models.CASCADE)
    teams = models.ManyToManyField('Team', related_name="teams")
    reunions = models.ManyToManyField('Reunion')
    softwares = models.ManyToManyField('Software', related_name='softwares')
    material_resources = models.ManyToManyField('MaterialResource')

    def __str__(self):
        return self.name

    def clean(self):
        if self.deadline < self.start_date:
            raise ValidationError("La date de fin ne peut pas être inférieure à la date de début.")
        super().clean()

    def can_be_started(self):
        """Returns True if the task can be started based on the start date of other tasks."""
        unfinished_tasks = Task.objects.filter(
            is_done=False, start_date__lt=self.start_date
        )
        return not unfinished_tasks.exists()


class Product(models.Model):
    TYPE_CHOICES = (
        ('Cahier de charges', 'CD'),
        ('Document de conception', 'DC'),
        ('Code source', 'CS'),
        ('Code exécutable', 'CE'),
        ('Rapport de test', 'RT'),
        ('Manuel', 'MA',),
    )
    name = models.CharField(max_length=255, db_index=True)
    description = models.TextField(blank=True, null=True)
    type = models.CharField(max_length=30, choices=TYPE_CHOICES)
    creation_date = models.DateField()
    task_associated = models.ForeignKey(Task, related_name='products', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name


class Reunion(models.Model):
    object = models.CharField(max_length=255, db_index=True)
    date = models.DateField()
    task_associated = models.ForeignKey(Task, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.object


class MeetingReport(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    reunion = models.ForeignKey(Reunion, on_delete=models.CASCADE)
    date = models.DateField()
    content = models.TextField()

    def __str__(self):
        return self.name


class SummaryReport(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    project = models.ForeignKey('Project', on_delete=models.CASCADE, null=True)
    meeting_reports = models.ManyToManyField(MeetingReport)
    date = models.DateField()

    def __str__(self):
        return self.name


class Agent(models.Model):
    matricule = models.CharField(max_length=10, unique=True)
    first_name = models.CharField(max_length=255, db_index=True)
    last_name = models.CharField(max_length=255, db_index=True)
    birth_date = models.DateField()
    recruitment_date = models.DateField()
    qualification = models.CharField(max_length=255)
    expertise_areas = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.first_name} {self.last_name} "


class Team(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    leader = models.OneToOneField(Agent, related_name='teams_leader', on_delete=models.SET_NULL, null=True)
    members = models.ManyToManyField(Agent, related_name='team_memberships')
    tasks = models.ManyToManyField(Task, related_name="tasks_todo")

    def __str__(self):
        return f"{self.name} team, led by {self.leader} "


class MaterialResource(models.Model):
    TYPE_CHOICES = (
        ('Partagée', 'P'),
        ('Exclusif', 'E'),
    )
    name = models.CharField(max_length=255, db_index=True)
    usage_mode = models.CharField(max_length=10, choices=TYPE_CHOICES)

    def __str__(self):
        return self.name


class Software(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

manager/project/templates/project/resources/add_material.html
{% extends 'project/base.html' %}

{% block content %}
    <h1 class="mb-6 px-8 text-3xl">Ajouter un matériel</h1>
    <form class="mt-6 px-8 space-y-4 text-start" method="post" action=".">
        {% csrf_token %}
        <div>
            <label for="id_name">Nom :</label><br>
            <input id="id_name" name="name" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label for="id_usage_mode">Mode d'utilisation :</label><br>
            <select id="id_usage_mode" name="usage_mode" class="w-full py-4 px-6 bg-slate-500 text-white">
                <option value="Partagée">Partagée</option>
                <option value="Exclusif">Exclusif</option>
            </select>
        </div>

        <div>
            <button type="submit" class="py-4 px-8 bg-green-600 hover:bg-green-400 text-white hover:text-gray-800">Créer</button>
        </div>
    </form>
{% endblock %}

manager/project/templates/project/resources/add_software.html
{% extends 'project/base.html' %}

{% block content %}
    <h1 class="mb-6 px-8 text-3xl">Ajouter un matériel</h1>
    <form class="mt-6 px-8 space-y-4 text-start" method="post" action=".">
        {% csrf_token %}
        <div>
            <label for="id_name">Nom :</label><br>
            <input id="id_name" name="name" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>
        <div>
            <label for="leader">Task associated (optional)</label><br>
            <select id="leader" name="task" class="w-full py-4 px-6 bg-slate-500 text-white">
                <option value="">Select a task associated</option>
                {% for task in tasks %}
                    <option value="{{ task.id }}">{{ task.name }}</option>
                {% endfor %}
            </select>
        </div>

        
        <div>
            <button type="submit" class="py-4 px-8 bg-green-600 hover:bg-green-400 text-white hover:text-gray-800">Créer</button>
        </div>
    </form>
{% endblock %}

manager/project/templates/project/resources/edit_material.html
{% extends 'project/base.html' %}

{% block content %}
    <h1 class="mb-6 px-8 text-3xl">Editer un matériel</h1>
    <form class="mt-6 px-8 space-y-4 text-start" method="post" action="{% url 'project:edit_material' material.id %}">
        {% csrf_token %}
        <div>
            <label for="id_name">Nom :</label><br>
            <input id="id_name" name="name" value="{{ material.name }}" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label for="id_usage_mode">Mode d'utilisation :</label><br>
            <select value="{{ material.usage_mode }}" id="id_usage_mode" name="usage_mode" class="w-full py-4 px-6 bg-slate-500 text-white">
                <option value="Partagée">Partagée</option>
                <option value="Exclusif">Exclusif</option>
            </select>
        </div>

        <div>
            <button type="submit" class="py-4 mt-8 px-8 bg-green-600 hover:bg-green-400 text-white hover:text-gray-800">Enregistrer les modifications</button>
        </div>
    </form>
{% endblock %}

manager/project/templates/project/resources/edit_software.html
{% extends 'project/base.html' %}

{% block content %}
    <h1 class="mb-6 px-8 text-3xl">Modifier un logiciel</h1>
    <form class="mt-6 px-8 space-y-4 text-start" method="post" action="{% url 'project:edit_software' software.id %} ">
        {% csrf_token %}
        <div>
            <label for="id_name">Nom :</label><br>
            <input id="id_name" value="{{ software.name }}" name="name" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label for="leader">Task associated</label><br>
            <select id="leader" name="task" class="w-full py-4 px-6 bg-slate-500 text-white">
                <option value="">{{ software.task }}</option>
                {% for task in tasks %}
                    <option value="{{ task.id }}">{{ task.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <button type="submit" class="py-4 px-8 bg-green-600 hover:bg-green-400 text-white hover:text-gray-800">Enregistrer</button>
        </div>
    </form>
{% endblock %}

manager/project/templates/project/resources/materials.html
{% extends 'project/base.html' %}

{% block content %}
    <div class="w-full flex justify-between items-center p-3">
      <h2 class="text-xl font-semibold">Materials resources</h2>
        <a href="{% url 'project:add_material' %}" >
            <button id="openModalBtn" class="flex items-center bg-green-600  hover:bg-green-400  text-white hover:text-gray-800   border border-fuchsia-00 hover:border-green-100  font-semibold py-2 px-4 rounded-md transition-colors duration-300">
                <svg class="w-4 h-4 mr-2 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
                </svg>
                <p class="text-white">New Material</p>
            </button>
        </a>
    </div>
    <!--==========-->
    <div class="w-full flex justify-center p-1 mb-4">
        <div class="relative w-full">
            <form method="GET" action="#">
                <input type="text" name="quest" class="w-full backdrop-blur-sm bg-white/20 py-2 pl-10 pr-4 rounded-lg focus:outline-none border-2 border-gray-100 focus:border-green-600 transition-colors duration-300" placeholder="Search...">
                <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                    <button type="submit">
                        <svg class="w-4 h-4 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
    </div>


    <!--==============-->


    <table class="min-w-full border-collapse block md:table">
		<thead class="block md:table-header-group">
			<tr class="border border-grey-500 md:border-none block md:table-row absolute -top-full md:top-auto -left-full md:left-auto  md:relative ">
				<th class="bg-slate-800 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">Nom</th>
				<th class="bg-slate-800 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">Mode d'utilisation</th>
				<th class="bg-slate-800 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">Actions </th>

			</tr>
		</thead>

            <tbody class="  block md:table-row-group">
                 {% for material  in materials %}
                    <tr class="bg-slate-600 text-white border border-grey-500 md:border-none block md:table-row">
                        <td class="p-2 md:border md:border-grey-500 text-left block md:table-cell"><span class="inline-block w-1/3 md:hidden font-bold">Nom</span>{{ material.name }}</td>
                        <td class="p-2 md:border md:border-grey-500 text-left block md:table-cell"><span class="inline-block w-1/3 md:hidden font-bold">Mode d'utilisation</span> {{  material.usage_mode }}</td>
                        <td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
                            <span class="inline-block w-1/3 md:hidden font-bold">Actions</span>
                            <a href="{% url 'project:edit_material' material.id %}"><button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-2 border border-blue-500 rounded">Edit</button></a>
                            <a href="{% url 'project:delete_material' material.id  %}"><button class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 border border-red-500 rounded">Delete</button></a>
                        </td>
                    </tr>
                 {% empty %}
                    <tr class="bg-slate-300 ">
                      <td class="p-2 md:border md:border-grey-500 text-center block md:table-cell"colspan="7">Aucun materiel trouvé.</td>
                    </tr>
                {% endfor %}
            </tbody>

	</table>



{% endblock %}

manager/project/templates/project/resources/softwares.html
{% extends 'project/base.html' %}

{% block content %}
    <div class="w-full flex justify-between items-center p-3">
      <h2 class="text-xl font-semibold">Softwares </h2>
        <a href="{% url 'project:add_software' %}" >
            <button id="openModalBtn" class="flex items-center bg-green-600  hover:bg-green-400  text-white hover:text-gray-800   border border-fuchsia-00 hover:border-green-100  font-semibold py-2 px-4 rounded-md transition-colors duration-300">
                <svg class="w-4 h-4 mr-2 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
                </svg>
                <p class="text-white">New Software</p>
            </button>
        </a>
    </div>
    <!--==========-->
    <div class="w-full flex justify-center p-1 mb-4">
        <div class="relative w-full">
            <form method="GET" action="{% url 'project:search_software' %}">
                <input type="text" name="quest" class="w-full backdrop-blur-sm bg-white/20 py-2 pl-10 pr-4 rounded-lg focus:outline-none border-2 border-gray-100 focus:border-green-600 transition-colors duration-300" placeholder="Search...">
                <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                    <button type="submit">
                        <svg class="w-4 h-4 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
    </div>


    <!--==============-->


    <table class="min-w-full border-collapse block md:table">
		<thead class="block md:table-header-group">
			<tr class="border border-grey-500 md:border-none block md:table-row absolute -top-full md:top-auto -left-full md:left-auto  md:relative ">
				<th class="bg-slate-800 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">Nom</th>
				<th class="bg-slate-800 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">Associated task</th>
				<th class="bg-slate-800 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">Actions </th>
			</tr>
		</thead>

        <tbody class="  block md:table-row-group">
             {% for software  in softwares %}
                <tr class="bg-slate-600 text-white border border-grey-500 md:border-none block md:table-row">
                    <td class="p-2 md:border md:border-grey-500 text-left block md:table-cell"><span class="inline-block w-1/3 md:hidden font-bold">Nom</span>{{ software.name }}</td>
                    <td class="p-2 md:border md:border-grey-500 text-left block md:table-cell"><span class="inline-block w-1/3 md:hidden font-bold">Associated Task</span>{{ software.task }}</td>

                    <td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
                        <span class="inline-block w-1/3 md:hidden font-bold">Actions</span>
                        <a href="{% url 'project:edit_software' software.id %}"><button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-2 border border-blue-500 rounded">Edit</button></a>
                        <a href="{% url 'project:delete_software' software.id %}"><button class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 border border-red-500 rounded">Delete</button></a>
                    </td>
                </tr>
             {% empty %}
                <tr class="bg-slate-300 ">
                  <td class="p-2 md:border md:border-grey-500 text-center block md:table-cell"colspan="7">Aucun logiciel trouvé.</td>
                </tr>
            {% endfor %}
        </tbody>

	</table>



{% endblock %}